# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d1dab90abce60cef82075757a6a7220edc96d69bd8dc66d1938341df96cd6a1f62bcb44564421327b6a057253941995c949084f49f3b1b43b260b611347a309

test:
  secret_key_base: 9d0102202e949d5000fca93b1ba913017c98848ceda6397764894470af46bf67fe78725a302d7986d903417aac21fbe1fca667df52774a5e4014e69770df9a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
